# add the linters you want stickler to use for this project
linters:
  rubocop:
    display_cop_names: true
    # indicate where is the config file for stylelint
    config: "./rubocop.yml"

files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"

