inherit_from: .rubocop_todo.yml

# Exceptions for general Ruby projects.
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Include: ["app/controllers/*"]
  Max: 20

# Exceptions for RSpec files.
Metrics/BlockLength:
  ExcludedMethods: ['describe']